DELIMITER $$
CREATE TABLE admin (
  id_admin INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE pegawai (
  id_pegawai INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE login (
  id_login INT AUTO_INCREMENT PRIMARY KEY,
  id_admin INT NULL,
  id_pegawai INT NULL,
  waktu_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_login_admin FOREIGN KEY (id_admin) REFERENCES admin(id_admin)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_login_pegawai FOREIGN KEY (id_pegawai) REFERENCES pegawai(id_pegawai)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE lokasi (
  id_lokasi INT AUTO_INCREMENT PRIMARY KEY,
  nama_lokasi VARCHAR(100) NOT NULL,
  lokasi VARCHAR(100) NOT NULL,
  deskripsi TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_lokasi (nama_lokasi, lokasi)
);

CREATE TABLE dispenser (
  id_dispenser INT AUTO_INCREMENT PRIMARY KEY,
  id_lokasi INT NOT NULL,
  kondisi ENUM('AKTIF','RUSAK','PERBAIKAN') DEFAULT 'AKTIF',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dispenser_lokasi FOREIGN KEY (id_lokasi) REFERENCES lokasi(id_lokasi)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE laporan_penggantian (
  id_laporan INT AUTO_INCREMENT PRIMARY KEY,
  id_dispenser INT NOT NULL,
  id_pegawai INT NOT NULL,
  jumlah_tisu INT NOT NULL,
  keterangan TEXT,
  waktu TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lp_disp FOREIGN KEY (id_dispenser) REFERENCES dispenser(id_dispenser)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_lp_peg FOREIGN KEY (id_pegawai) REFERENCES pegawai(id_pegawai)
    ON DELETE CASCADE ON UPDATE CASCADE
);